# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85aa2c5801a7a72efb1c77180823e07ae540dffc7ac85cbb54662a0c936f68bc6dbeed5366fb4a5542c5583b515b382d90a3fe3c22c5bdb6f17f72362ff81acd

test:
  secret_key_base: 64747ddbb0d6295e3ecf8451058e213751bf6c098fd15ed179f1211ecd262bf86d5d9e68991777f5aa36ecc3585d8340e1e0a403c8dcaa4322a67c63be86ad94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
